services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper-service
    ports:
      - "${WHISPER_HOST_PORT:-0}:9000"
    environment:
      - LANG=C.UTF-8
      - POETRY_VENV=/app/.venv
    volumes:
      - whisper_models:/root/.cache/whisper
    working_dir: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 60s
    networks:
      - whisper-network

networks:
  whisper-network:
    driver: bridge
    name: whisper-network

volumes:
  whisper_models:
    driver: local
    name: whisper_models
